### ISSUE TITLE
consider moving to nebula-contrib org?

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/nebula-carina#1]
Dear @SwordElucidator 

This project is amazing :) would you consider moving this project to the NebulaGraph Community Org: https://github.com/nebula-contrib/ ?

It's OK if it's not comfortable to do so, just like the norm(https://github.com/zhihu/norm) project isn't under nebula-contrib, but we would ask creators in case they would like to.

Thanks!

BR//Wey

**Comment by SwordElucidator** [comment]
Yeah I would like to do so, though I'm still considering about the implementation and project structure. I would spend some more time to learn from the repos in the community and improve this repo, then it would be nice to move it.

**Comment by wey-gu** [comment]
> Yeah I would like to do so, though I'm still considering about the implementation and project structure. I would spend some more time to learn from the repos in the community and improve this repo, then it would be nice to move it.

That's awesome, please take your time @SwordElucidator.

For anything I could help out, let me know.

**Comment by SwordElucidator** [comment]
@wey-gu  Just a small question. I found that currently an edge will only have one edge type. Will there be any plans to support multi edge types for a single edge in the future? e.g. a human relation may consist multiple aspects. Obviously different aspects could be represented by different edges, but I still want to make sure that this will still be the best practice in the future. Thank you!

**Comment by wey-gu** [comment]
The edge type is tied with edge identity due to the edge type field is part of its 4-tuple key design. Unlike vertex.

Thus it's kind of double standard when we're talking about types of vertex to vertex instance vs types of edge to edge instance.

**Comment by SwordElucidator** [comment]
@wey-gu  Thank you for reply! I'll contact you ;)

**Comment by wey-gu** [comment]
@Shinji-IkariG could you please kindly help @SwordElucidator with the repo moving?

**Comment by Shinji-IkariG** [comment]
As admin please transfer the repo to me and I will transfer to nebula-contrib as soon as I receive the repo

**Comment by SwordElucidator** [comment]
@Shinji-IkariG  I've sent the transfer request. Please check it.
