### ISSUE TITLE
vid type is FIXED_STRING, when insert vid='1234',vid will be transform to int type, lead to insert ngql failed.

### ISSUE THREAD

**Issue by wyicefog** [nebula-contrib/nebula-carina#10]
vid type is FIXED_STRING.

code:
 `GitProjectVertex(vid='1234', git_project=GitProject(project_id='1234', project_name='test', update_time=datetime.now())).upsert()` 

ERROR CODE: -1005 when executing NGQL [UPSERT VERTEX ON git_project 1234 SET project_id = "1234", project_name = "test", update_time = datetime("2023-02-13 20:44:05.323014");]
Wrong vertex id type: 1234

Please solve this problem.

**Comment by SwordElucidator** [comment]
Got the problem. Will try to fix it soon.

**Comment by SwordElucidator** [comment]
This is caused by pydantic behavior. Just changed the vid type to strict int & str
