### ISSUE TITLE
missing pin for pydantic = "==1.10.8" results in ImportError

### ISSUE THREAD

**Issue by johnny-smitherson** [nebula-contrib/nebula-carina#23]
Installing package from `main` branch then importing 

`from nebula_carina.models.migrations import make_migrations, migrate` 

results in this error: 

`ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/home/user/.local/lib/python3.10/site-packages/pydantic/fields.py)`

[workaround: pydantic = "==1.10.8"](https://stackoverflow.com/questions/77469094/importerror-cannot-import-name-modelfield-from-pydantic-fields/77469213#77469213)

**Comment by wey-gu** [comment]
@johnny-smitherson would you mind PR to pin it?

Thanks!

**Comment by wey-gu** [comment]
> I think this should be closable now. 
> 
> No need to pin pydantic anymore

Thanks @magnudae ❤️
