### ISSUE TITLE
Typo environment variable in readme: nebula_carina_paths -> nebula_model_paths

### ISSUE THREAD

**Issue by johnny-smitherson** [nebula-contrib/nebula-carina#24]
In readme it's this: https://github.com/search?q=repo%3Anebula-contrib%2Fnebula-carina%20nebula_carina_paths&type=code

but in the code it's this: https://github.com/search?q=repo%3Anebula-contrib%2Fnebula-carina%20model_paths&type=code

**Comment by wey-gu** [comment]
Thanks @johnny-smitherson , would you mind PR to fix/align them all?

Or I will fix them later :)

Thanks a lot!

**Comment by magnudae** [comment]
This is fixed

**Comment by wey-gu** [comment]
> This is fixed

Thanks @magnudae ❤️
